### ISSUE TITLE
Key Error when exiting QGIS

### ISSUE THREAD

**Issue by JaumeFigueras** [JaumeFigueras/GisFIRE-SpreadSimulation#1]
KeyError: 'GisFIRE-SpreadSimulation' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 437, in unloadPlugin
    _unloadPluginModules(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 466, in _unloadPluginModules
    for path in sys.modules[mod].__path__:
  File "", line 1174, in __iter__
  File "", line 1162, in _recalculate
  File "", line 1158, in _get_parent_path
KeyError: 'GisFIRE-SpreadSimulation'

**Comment by JaumeFigueras** [comment]
Added prints to help on debug in this [commit](https://github.com/JaumeFigueras/GisFIRE-SpreadSimulation/commit/96e825ef894a9dd9100d5f37fc52db32411b8f32). Now can't reproduce the error anymore.
Maybe it is related with project slots

**Comment by JaumeFigueras** [comment]
Solved in master.
Deleted imports
